In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns',None)

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

In [4]:
df_alquileres=pd.read_csv("listings.csv")

display(df_alquileres.head(2))
print("="*100)
display(df_alquileres.tail(2))
print("="*100)
display(df_alquileres.sample(2))

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,18674,Huge flat for 8 people close to Sagrada Familia,71615,1462508358342835057,Mireia,Eixample,la Sagrada Família,41.40556,2.17262,Entire home/apt,NaN,1,54,2025-11-19,0.35,24,115,9,Spain - National registration number<br />ESFC...
1,2031134,Sagrada Familia-auditorium. FREE WI-FI.,9100900,1462794940868112780,Miguel,Eixample,el Fort Pienc,41.40001,2.18416,Entire home/apt,NaN,2,453,2025-12-02,3.16,1,294,52,Barcelona - Regional registration number<br />...

====================================================================================================

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
18175,1574678224497628954,Cuarto privado para estancias cortas,731296157,1564548850394018347,Shirley Alisson,Eixample,la Dreta de l'Eixample,41.386200,2.16769,Private room,NaN,2,0,NaN,NaN,5,345,0,Barcelona - Regional registration number<br />...
18176,1574760542225568017,comfortable sunny quiet central located,258156372,1469363937744404825,Jorge Antonio,Ciutat Vella,el Raval,41.381548,2.17034,Entire home/apt,NaN,7,0,NaN,NaN,2,15,0,Spain - National registration number<br />Exem...

====================================================================================================

,id,name,host_id,host_profile_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
3147,18459019,AB Marina Apartment P-III,4459553,1462535697208324401,David,Eixample,el Fort Pienc,41.39908,2.17836,Entire home/apt,NaN,1,127,2025-12-01,1.26,225,336,26,Barcelona - Regional registration number<br />...
5240,34387007,Habitación doble muy céntrica y luminosa,94833392,1467143523728383835,Joan,Eixample,Sant Antoni,41.38208,2.16218,Private room,NaN,3,6,2019-10-21,0.07,1,0,0,NaN